OpenRouterTeam/openrouter-runner

- modal/runner/containers/__init__.py
> add orca 2

- modal/runner/containers/__init__.py
> feat: add intel neural chat

- .github/CONTRIBUTING.md
- README.md
- example.env
- modal/runner/README.md
- modal/runner/containers/__init__.py
- modal/tuner/README.md
- pyproject.toml
- scripts/shared.ts
- scripts/test-alpaca.ts
- scripts/test-lora.ts
- scripts/test-punctuator.ts
- scripts/test-simple.ts
> Noromaid, and improve clarity

- modal/runner/containers/__init__.py
- modal/runner/containers/vllm_top.py
- modal/runner/shared/sampling_params.py
- modal/shared/protocol.py
- scripts/shared.ts
> fix: vllm container for 20B model

- modal/runner/containers/__init__.py
> feat: add toppy 7B

- modal/runner/__init__.py
- modal/runner/containers/__init__.py
- modal/runner/containers/lorean_7b.py
- modal/runner/containers/vllm_a100_128k.py
- modal/runner/containers/vllm_a100_200k.py
- modal/runner/containers/vllm_a100_32k.py
- modal/runner/containers/vllm_awq.py
- modal/runner/containers/vllm_mid.py
- modal/runner/containers/vllm_top.py
- scripts/test-alpaca.ts
- scripts/test-large-prompt.ts
- scripts/test-simple.ts
> feat: Add psyfighter

- modal/shap-e/__init__.py
> feat: migrate shap-e to modal

- modal/runner/containers/__init__.py
- modal/runner/containers/vllm_unified.py
> feat: dolphin mixtral

- .github/workflows/lint.yml
- modal/punctuator/__init__.py
- modal/runner/__init__.py
- modal/runner/containers/lorean_7b.py
- modal/runner/containers/vllm_unified.py
- modal/runner/endpoints/completion.py
- modal/runner/engines/lorean.py
- modal/runner/engines/vllm.py
- modal/runner/shared/clean.py
- modal/runner/shared/common.py
- modal/runner/shared/download.py
- modal/shap-e/__init__.py
- modal/tuner/__init__.py
- modal/tuner/containers/mistral_7b_lora.py
- modal/tuner/endpoints/create_lora.py
- modal/tuner/endpoints/list_lora.py
- modal/tuner/shared/common.py
- pyproject.toml
:v: happy nye :) recovering from some shows last night & thought i'd tidy up this linter comment thread from last PR while my brain defogs lol
https://github.com/OpenRouterTeam/openrouter-runner/pull/31#discussion_r1437131872
now it should be checking the linting + formatting rules
> ci: fix linter action to also check formatting

- modal/runner/containers/__init__.py
Removes models that are currently unused.
> remove unused models

- modal/runner/containers/__init__.py
bagel-34b-v0.2 was hitting OOM issues on anything smaller
> add bagel-34b-v0.2 and chronos-hermes-13b-v2

- modal/runner/README.md
- modal/runner/containers/vllm_unified.py
Adds a Sentry integration to the VLLM runner container
> add sentry to vllm container

- modal/runner/containers/__init__.py
- modal/runner/containers/vllm_unified.py
Allow testing of new models in isolation
> isolate bagel inference

- modal/shared/volumes.py
Getting some errors from this function being called with a `str`
> fix path serialization

- modal/runner/containers/vllm_unified.py
- modal/shared/logging.py
a potential fix for https://github.com/OpenRouterTeam/openrouter-runner/pull/49#issuecomment-1891077379
inspired from this [python-json-logger package](https://github.com/madzak/python-json-logger/blob/master/src/pythonjsonlogger/jsonlogger.py#L217)
> fix: automatically attach logging extras into the log record json

- .github/workflows/release-prod.yml
releases to prod env on push to main
just tested this in dev locally w/ act:
> ci: release to modal main env on push to main

- modal/runner/containers/vllm_unified.py
had some time to fix this bug that came up in chat earlier -- was able to successfully test bagel on our dev env
> fix: unset CUDA_VISIBLE_DEVICES in vLLM containers to patch Ray bug

- modal/runner/endpoints/completion.py
first step in getting more granular cost breakdown for GPU time spent in modal
simply times the entire async generation block (which includes cold start + generation + any latency to send back to client)
might be over-reporting slightly because of time to send to client, but thats preferable to under-reporting
tested in dev:
> feat: remote generation on GPU timer to track costs

- modal/runner/containers/__init__.py
- modal/runner/containers/vllm_unified.py
- modal/shared/protocol.py
> feat: move phi-2 to a dedicated container, remove backup models

- modal/shared/logging.py
based on docs here: https://docs.sentry.io/platforms/python/data-management/sensitive-data/
> fix: sentry scrubbing

- modal/runner/__init__.py
This is needed because Modal volumes get corrupted by async downloads
Also enables `--force` on the all-models downloader
> Make model downloading synchronous again

- modal/runner/engines/vllm.py
- modal/shared/protocol.py
in preparation for sending gpu timing information in a proper usage struct -- getting the refactor started & fixing the current behavior of sending `0` token counts
example streaming:
```
...
data: {"text": " arena", "prompt_tokens": 23, "completion_tokens": 290, "usage": {"prompt_tokens": 23, "completion_tokens": 290, "total_tokens": 313}, "done": false}
data: {"text": ".", "prompt_tokens": 23, "completion_tokens": 291, "usage": {"prompt_tokens": 23, "completion_tokens": 291}, "done": false}
data: {"text": "", "prompt_tokens": 23, "completion_tokens": 292, "usage": {"prompt_tokens": 23, "completion_tokens": 292}, "done": false}
data: {"text": "", "prompt_tokens": 23, "completion_tokens": 292, "usage": {"prompt_tokens": 23, "completion_tokens": 292}, "done": true}
```
example non …
> fix: running total of tokens for streams

- .github/workflows/release-prod.yml
- modal/runner/engines/vllm.py
- modal/shared/protocol.py
Adding `finish_reason` to the runner's response
> feat: add finish_reason to the protocol

- modal/runner/containers/vllm_unified.py
- modal/runner/engines/vllm.py
- modal/shared/protocol.py
followup to #64 -- deprecating the top level usage fields
> refactor: deprecate old usage fields & simplify vllm generate fn

- modal/runner/__init__.py
- modal/runner/containers/__init__.py
- modal/runner/containers/vllm_unified.py
- modal/runner/endpoints/completion.py
- modal/runner/engines/vllm.py
- modal/shared/logging.py
- modal/shared/protocol.py
- scripts/shared.ts
- scripts/test-dynamic-model.ts
pause dynamic model addition development & simplify model:container mapping to be 1-to-1
this allows for easier cost tracking by model, directly inside of modal instead of datadog
> refactor: move all models to their own unique containers

- modal/runner/containers/vllm_unified.py
> fix: add a concurrency_limit to noromaidmixtral & bagel

- modal/runner/containers/vllm_unified.py
- modal/runner/engines/vllm.py
- modal/runner/shared/common.py
- modal/shared/protocol.py
> feat: add support for h100s & bump backlog limit

- modal/runner/containers/vllm_unified.py
- modal/runner/endpoints/completion.py
> perf: serve quantized versions of noromaid mixtral & bagel

- modal/runner/containers/vllm_unified.py
> chore: temporarily comment out keep_warm

- modal/runner/containers/vllm_unified.py
to enable if we see a buncha usage and we wanna never cold start
> perf: always keep one midnight rose

- modal/runner/containers/vllm_unified.py
moved this model over to lepton where it always is on -- no need to keep it warm here still
> perf: let bagel scale to zero

- modal/runner/containers/vllm_unified.py
experimenting with moving this model to lepton as well -- so for now removing the keep_warm=1
> perf: let midnight rose scale to zero

- modal/runner/containers/vllm_unified.py
> perf: let noromaid mixtral scale to zero

- modal/runner/containers/vllm_unified.py
additionally removing the ones that have no-code deploys on lepton now
> fix: remove deprecated models bagel & psyfighter1
